name: coveralls
on:
    pull_request:
        branches:
            - master
    push:
        branches:
            - master
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: pnpm/action-setup@v2
              with:
                  version: latest
                  run_install: false

            - uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: 'pnpm'

            - run: |
                  pnpm install --reporter=append-only --frozen-lockfile
                  pnpm run test:coverage

            - name: Coveralls
              uses: coverallsapp/github-action@master
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
